from __future__ import annotations

CATEGORY_KNOWLEDGE = [
    {
        "slug": "work-tech",
        "name": "Work Tech",
        "keywords": [
            "laptop",
            "study",
            "coding",
            "office",
            "desk",
            "developer",
            "portable",
            "workstation",
            "lamp",
            "setup",
        ],
        "related_categories": ["travel-everyday", "wellness"],
    },
    {
        "slug": "home-living",
        "name": "Home Living",
        "keywords": [
            "blanket",
            "throw",
            "diffuser",
            "calm",
            "home",
            "cozy",
            "bedside",
            "room",
            "sofa",
            "decor",
        ],
        "related_categories": ["beauty-care", "wellness"],
    },
    {
        "slug": "kitchen-dining",
        "name": "Kitchen Dining",
        "keywords": [
            "coffee",
            "press",
            "kitchen",
            "cutting",
            "board",
            "brew",
            "meal",
            "prep",
            "dining",
        ],
        "related_categories": ["home-living", "wellness"],
    },
    {
        "slug": "wellness",
        "name": "Wellness",
        "keywords": [
            "yoga",
            "fitness",
            "water",
            "hydration",
            "stretching",
            "workout",
            "bottle",
            "wellness",
            "routine",
        ],
        "related_categories": ["travel-everyday", "home-living"],
    },
    {
        "slug": "travel-everyday",
        "name": "Travel Everyday",
        "keywords": [
            "travel",
            "bag",
            "weekender",
            "tote",
            "carry",
            "trip",
            "commuter",
            "overnight",
            "daily",
        ],
        "related_categories": ["work-tech", "wellness"],
    },
    {
        "slug": "beauty-care",
        "name": "Beauty Care",
        "keywords": [
            "beauty",
            "skincare",
            "skin",
            "mirror",
            "routine",
            "care",
            "self care",
            "gentle",
        ],
        "related_categories": ["home-living", "travel-everyday"],
    },
]

PRODUCT_KNOWLEDGE = [
    {
        "id": 1,
        "name": "NovaBook Flex 13",
        "slug": "novabook-flex-13",
        "brand": "Nova",
        "category_slug": "work-tech",
        "category_name": "Work Tech",
        "short_description": "A lightweight laptop for study, travel, and focused work.",
        "summary": "Slim form factor and reliable battery life for writing, planning, and mobile work.",
        "price": "18.90",
        "accent_color": "#EEF4FF",
        "featured": True,
        "absolute_url": "/products/novabook-flex-13",
        "tags": ["laptop", "study", "portable", "office", "coding", "student", "work"],
        "complements": ["transit-weekender", "puresip-bottle", "luma-desk-light"],
    },
    {
        "id": 2,
        "name": "Luma Desk Light",
        "slug": "luma-desk-light",
        "brand": "Luma",
        "category_slug": "work-tech",
        "category_name": "Work Tech",
        "short_description": "An adjustable desk lamp for compact work corners.",
        "summary": "Soft illumination with a compact footprint for study desks and small home offices.",
        "price": "2.40",
        "accent_color": "#FFF6E8",
        "featured": False,
        "absolute_url": "/products/luma-desk-light",
        "tags": ["desk", "lamp", "study", "office", "setup", "light"],
        "complements": ["novabook-flex-13", "glowmirror-mini"],
    },
    {
        "id": 3,
        "name": "CloudRest Throw",
        "slug": "cloudrest-throw",
        "brand": "Hush",
        "category_slug": "home-living",
        "category_name": "Home Living",
        "short_description": "A soft throw blanket for reading nooks and sofas.",
        "summary": "Lightweight warmth and neutral texture for living rooms and bedroom corners.",
        "price": "1.90",
        "accent_color": "#F6F1FF",
        "featured": False,
        "absolute_url": "/products/cloudrest-throw",
        "tags": ["blanket", "throw", "home", "cozy", "reading", "sofa"],
        "complements": ["aromanest-diffuser", "calmskin-set"],
    },
    {
        "id": 4,
        "name": "AromaNest Diffuser",
        "slug": "aromanest-diffuser",
        "brand": "Nest",
        "category_slug": "home-living",
        "category_name": "Home Living",
        "short_description": "A ceramic diffuser for small rooms and calmer evenings.",
        "summary": "Quiet mist output with a soft matte finish for desks, shelves, and bedside tables.",
        "price": "2.70",
        "accent_color": "#EFF8F1",
        "featured": True,
        "absolute_url": "/products/aromanest-diffuser",
        "tags": ["diffuser", "calm", "home", "bedside", "relax", "room"],
        "complements": ["cloudrest-throw", "calmskin-set"],
    },
    {
        "id": 5,
        "name": "BrewMate Press",
        "slug": "brewmate-press",
        "brand": "BrewMate",
        "category_slug": "kitchen-dining",
        "category_name": "Kitchen Dining",
        "short_description": "A compact French press for slower morning coffee.",
        "summary": "Easy-grip handle and a compact size for one or two cups at home.",
        "price": "2.20",
        "accent_color": "#FFF3EC",
        "featured": False,
        "absolute_url": "/products/brewmate-press",
        "tags": ["coffee", "press", "brew", "morning", "kitchen", "cafe"],
        "complements": ["sliceboard-duo", "cloudrest-throw"],
    },
    {
        "id": 6,
        "name": "SliceBoard Duo",
        "slug": "sliceboard-duo",
        "brand": "Hearth",
        "category_slug": "kitchen-dining",
        "category_name": "Kitchen Dining",
        "short_description": "A bamboo cutting board set for everyday meal prep.",
        "summary": "Two versatile sizes with an easy fit for compact kitchens.",
        "price": "1.60",
        "accent_color": "#F5F0E8",
        "featured": False,
        "absolute_url": "/products/sliceboard-duo",
        "tags": ["cutting board", "kitchen", "prep", "bamboo", "meal"],
        "complements": ["brewmate-press", "puresip-bottle"],
    },
    {
        "id": 7,
        "name": "CoreBalance Mat",
        "slug": "corebalance-mat",
        "brand": "Core",
        "category_slug": "wellness",
        "category_name": "Wellness",
        "short_description": "A non-slip yoga mat for stretching and light training.",
        "summary": "Soft cushioning and stable grip for home workouts and warm-ups.",
        "price": "2.10",
        "accent_color": "#EEF7FF",
        "featured": True,
        "absolute_url": "/products/corebalance-mat",
        "tags": ["yoga", "mat", "stretching", "fitness", "workout", "wellness"],
        "complements": ["puresip-bottle", "transit-weekender"],
    },
    {
        "id": 8,
        "name": "PureSip Bottle",
        "slug": "puresip-bottle",
        "brand": "PureSip",
        "category_slug": "wellness",
        "category_name": "Wellness",
        "short_description": "An insulated bottle for water, tea, and daily routines.",
        "summary": "Clean shape and comfortable grip for work, class, or gym sessions.",
        "price": "1.35",
        "accent_color": "#F0FAFF",
        "featured": False,
        "absolute_url": "/products/puresip-bottle",
        "tags": ["water", "bottle", "hydration", "daily", "gym", "wellness"],
        "complements": ["corebalance-mat", "transit-weekender", "novabook-flex-13"],
    },
    {
        "id": 9,
        "name": "Transit Weekender",
        "slug": "transit-weekender",
        "brand": "Route",
        "category_slug": "travel-everyday",
        "category_name": "Travel Everyday",
        "short_description": "A compact travel bag for overnights and short city trips.",
        "summary": "Structured body and enough space for clothing, toiletries, and small essentials.",
        "price": "3.40",
        "accent_color": "#F2F4FF",
        "featured": True,
        "absolute_url": "/products/transit-weekender",
        "tags": ["travel", "bag", "weekender", "overnight", "trip", "carry"],
        "complements": ["novabook-flex-13", "puresip-bottle", "glowmirror-mini"],
    },
    {
        "id": 10,
        "name": "LinenCarry Tote",
        "slug": "linencarry-tote",
        "brand": "Linen",
        "category_slug": "travel-everyday",
        "category_name": "Travel Everyday",
        "short_description": "A minimal tote bag for markets, errands, and daily carry.",
        "summary": "Light structure and soft fabric blend for relaxed everyday trips.",
        "price": "1.10",
        "accent_color": "#F9F4EE",
        "featured": False,
        "absolute_url": "/products/linencarry-tote",
        "tags": ["tote", "bag", "carry", "daily", "market", "travel"],
        "complements": ["glowmirror-mini", "puresip-bottle"],
    },
    {
        "id": 11,
        "name": "GlowMirror Mini",
        "slug": "glowmirror-mini",
        "brand": "Glow",
        "category_slug": "beauty-care",
        "category_name": "Beauty Care",
        "short_description": "A portable LED mirror for desks, travel, and touch-ups.",
        "summary": "Soft integrated light and a compact size that slips easily into a bag.",
        "price": "1.75",
        "accent_color": "#FFF1F5",
        "featured": False,
        "absolute_url": "/products/glowmirror-mini",
        "tags": ["mirror", "beauty", "portable", "travel", "care", "touch-up"],
        "complements": ["calmskin-set", "transit-weekender", "linencarry-tote"],
    },
    {
        "id": 12,
        "name": "CalmSkin Set",
        "slug": "calmskin-set",
        "brand": "Calm",
        "category_slug": "beauty-care",
        "category_name": "Beauty Care",
        "short_description": "A gentle skincare starter set for simple routines.",
        "summary": "Balanced hydration and light cleansing for a low-friction daily routine.",
        "price": "2.95",
        "accent_color": "#F3F8F3",
        "featured": True,
        "absolute_url": "/products/calmskin-set",
        "tags": ["skincare", "skin care", "beauty", "care", "routine", "gentle"],
        "complements": ["glowmirror-mini", "aromanest-diffuser"],
    },
]

QUICK_PROMPTS = [
    "Suggest products for study and portable work",
    "Recommend add-ons for my cart",
    "Help me choose between wellness and travel essentials",
    "Find products for a calm home routine",
]
